"""Renderer — Registry v2 + runtime descriptors → rendered artifacts
(PR-3, ADR-026 R-1/R-3/R-4; docs/MODEL_ROUTING_DESIGN.md §6,
docs/PROVIDER_ABSTRACTION.md §3, docs/RUNTIME_ABSTRACTION_STRATEGY.md §4).

    registry.yaml  ─┐
                    ├─ render() ─► litellm-config.yaml      (models + role-* aliases → engine)
    providers/*.yaml┘             docker-compose.engine.yml (engine-slot materialization)
    capability vector             role_map.yaml             (ADR-020 shape for agentd)
                                  capability_report.yaml    (negotiation evidence)
                                  [engine-models.ini]       (multi-model preset)
                                  manifest.yaml             (hashes → drift detection)

Rules realized here:

- **Roles are the interface.** LiteLLM serves ``role-<role>`` aliases next
  to model aliases; both point at the engine slot through its neutral
  network alias ``engine`` (never the historical service name).
- **Capability negotiation at render time** (CF-6): for every role, every
  model in its resolution chain must satisfy the role contract on its
  runtime — tool calling (parser ∈ runtime parsers), JSON output, context
  — and be in a format the runtime serves. Failures are loud and name the
  missing capability; nothing fails silently at request time.
- **One engine slot, one runtime.** The active set must be servable by the
  selected runtime; conflicts are explained in plain language.
- **Rendered files are outputs.** Every artifact carries a GENERATED banner
  and a hash in the manifest; ``write_rendered`` refuses to overwrite a
  hand-edited artifact (drift) unless forced.
- **No runtime or hardware knowledge in this module.** Images, flags,
  parsers, devices come from descriptor data; this module fills templates.

Until the PR-7 cutover the renderer writes to a parallel path
(``<config>/rendered/``); the hand-written LiteLLM configs stay in place.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field

from agentd.capability import CapabilityVector, classify
from agentd.logging_setup import get_logger
from agentd.registry_v2 import ModelEntry, RegistryV2, Resolution, RoleContract
from agentd.runtime_descriptor import RuntimeDescriptor

log = get_logger("render")

#: Neutral network alias of the engine slot (ADR-026 R-3). New consumers
#: and every rendered artifact address the slot as ``engine:8000``.
ENGINE_HOST = "engine"
ENGINE_PORT = 8000
#: Historical compose service name of the slot (ADR-001) — kept for
#: compatibility; this constant is the only place code spells it.
ENGINE_SERVICE = "vllm"

ROLE_ALIAS_PREFIX = "role-"
RENDERED_DIRNAME = "rendered"
LITELLM_FILENAME = "litellm-config.yaml"
ENGINE_COMPOSE_FILENAME = "docker-compose.engine.yml"
ROLE_MAP_FILENAME = "role_map.yaml"
CAPABILITY_REPORT_FILENAME = "capability_report.yaml"
PRESET_FILENAME = "engine-models.ini"
MANIFEST_FILENAME = "manifest.yaml"
#: Every artifact name the renderer may own (drift scope).
MANAGED_FILENAMES = (
    LITELLM_FILENAME, ENGINE_COMPOSE_FILENAME, ROLE_MAP_FILENAME,
    CAPABILITY_REPORT_FILENAME, PRESET_FILENAME,
)

GENERATED_BANNER = (
    "GENERATED by local-ezai — do not edit. Rendered from "
    "config/models/registry.yaml + config/providers/*.yaml; change state "
    "with `local-ezai model …` or the Admin Center and re-render."
)
#: The stack's LiteLLM platform sections (not model data): master key from
#: the environment and the auto-RAG pre-call hook of the chat stack.
LITELLM_GENERAL_SETTINGS = {"master_key": "os.environ/LITELLM_MASTER_KEY"}
LITELLM_SETTINGS = {"callbacks": "litellm_custom_callbacks.auto_rag_handler"}
LOCAL_API_KEY = "not-needed-locally"

_PLACEHOLDER = re.compile(r"\{([a-z_]+)\}")


class RenderError(ValueError):
    """The generation cannot be rendered; the message lists every reason."""


class DriftError(RenderError):
    """A rendered artifact was edited by hand (or is unmanaged)."""


# ── inputs / outputs ─────────────────────────────────────────────────────────


class EmbeddingEntry(BaseModel):
    """The embedding route LiteLLM must keep serving (embeddings live on the
    dedicated embed server, outside the PAL — PROVIDER_ABSTRACTION §7).
    No defaults: the model name is data supplied by the caller."""

    alias: str
    model: str
    api_base: str


class CapabilityCheck(BaseModel):
    """One (role, model) negotiation result — evidence for approvals."""

    role: str
    model: str
    runtime: str
    position: str  # "primary" | "fallback"
    ok: bool
    checks: dict[str, bool] = Field(default_factory=dict)
    failures: list[str] = Field(default_factory=list)


class RenderResult(BaseModel):
    generation: int
    runtime: str
    capability_class: str
    accelerator: str
    served_models: list[str]
    #: filename → rendered text
    artifacts: dict[str, str]
    report: list[CapabilityCheck]


# ── template filling ─────────────────────────────────────────────────────────


def _fill(template: str, context: dict[str, str], origin: str) -> str:
    def substitute(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in context:
            raise RenderError(
                f"{origin}: unknown placeholder '{{{key}}}' — known: "
                + ", ".join(sorted(context)))
        return context[key]
    return _PLACEHOLDER.sub(substitute, template)


def _fill_deep(value: Any, context: dict[str, str], origin: str) -> Any:
    if isinstance(value, str):
        return _fill(value, context, origin)
    if isinstance(value, list):
        return [_fill_deep(v, context, origin) for v in value]
    if isinstance(value, dict):
        return {k: _fill_deep(v, context, origin) for k, v in value.items()}
    return value


def _merge(base: dict[str, Any], extra: dict[str, Any]) -> dict[str, Any]:
    """Deep-merge compose fragments: mappings recurse, lists concatenate,
    scalars from ``extra`` win."""
    merged = dict(base)
    for key, value in extra.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _merge(merged[key], value)
        elif isinstance(value, list) and isinstance(merged.get(key), list):
            merged[key] = [*merged[key], *value]
        else:
            merged[key] = value
    return merged


# ── capability negotiation (RUNTIME_ABSTRACTION §4) ──────────────────────────


def _effective_context(entry: ModelEntry, ctx_budget: int) -> int:
    return min(entry.context, ctx_budget) if entry.context > 0 else ctx_budget


def _ctx_budget(descriptor: RuntimeDescriptor, tuning: dict[str, str]) -> int:
    try:
        return int(tuning["ctx_size"])
    except ValueError as exc:
        raise RenderError(
            f"descriptor '{descriptor.runtime}': tuning.ctx_size must resolve "
            f"to an integer, got {tuning['ctx_size']!r}") from exc


def check_contract(model: str, entry: ModelEntry, descriptor: RuntimeDescriptor,
                   requires: RoleContract, capability_class: str,
                   accelerator: str = "none") -> tuple[dict[str, bool], list[str]]:
    """Does this model, served by this runtime on this class, satisfy a role
    contract? Returns (checks, failures) — failures name the missing
    capability. Shared by render-time negotiation and the catalog
    recommender (PR-4)."""
    checks: dict[str, bool] = {}
    failures: list[str] = []

    if entry.source:
        served = descriptor.source_for(entry.source) is not None
        checks["format"] = served
        if not served:
            failures.append(
                f"format: model '{model}' is {'/'.join(entry.source)} but "
                f"runtime '{descriptor.runtime}' serves "
                f"{', '.join(descriptor.serves_formats)} — install a served "
                "variant or select a runtime that serves it")

    if requires.tool_calling:
        parsers = descriptor.capabilities.tool_call_parsers
        ok = bool(entry.tool_call_format) and entry.tool_call_format in parsers
        checks["tool_calling"] = ok
        if not ok:
            declared = entry.tool_call_format or "<none declared>"
            failures.append(
                f"missing capability tool_calling: model '{model}' declares "
                f"tool_call_format '{declared}'; runtime '{descriptor.runtime}' "
                f"parses {', '.join(parsers) or '<none>'}")

    if requires.json_output:
        ok = descriptor.capabilities.json_output
        checks["json_output"] = ok
        if not ok:
            failures.append(
                f"missing capability json_output: runtime "
                f"'{descriptor.runtime}' has no constrained JSON decoding")

    if requires.min_context:
        budget = _ctx_budget(descriptor,
                             descriptor.tuning_for(capability_class, accelerator))
        effective = _effective_context(entry, budget)
        ok = effective >= requires.min_context
        checks["min_context"] = ok
        if not ok:
            failures.append(
                f"missing capability min_context: role needs "
                f"{requires.min_context} tokens; model '{model}' on "
                f"'{descriptor.runtime}' gets {effective} on class "
                f"{capability_class} (model context {entry.context or 'unset'}, "
                f"class budget {budget})")
    return checks, failures


def _check_model(role: str, model: str, position: str, entry: ModelEntry,
                 registry: RegistryV2, descriptors: dict[str, RuntimeDescriptor],
                 capability_class: str, accelerator: str) -> CapabilityCheck:
    descriptor = descriptors.get(entry.provider)
    if descriptor is None:
        return CapabilityCheck(
            role=role, model=model, runtime=entry.provider, position=position,
            ok=False,
            failures=[f"runtime '{entry.provider}' has no descriptor under "
                      "config/providers/ (known: "
                      + ", ".join(sorted(descriptors)) + ")"])
    checks, failures = check_contract(model, entry, descriptor,
                                      registry.roles[role].requires,
                                      capability_class, accelerator)
    return CapabilityCheck(role=role, model=model, runtime=descriptor.runtime,
                           position=position, ok=not failures, checks=checks,
                           failures=failures)


def negotiate(registry: RegistryV2, descriptors: dict[str, RuntimeDescriptor],
              capability_class: str, accelerator: str = "none") -> list[CapabilityCheck]:
    """Every role × every model in its resolution chain against the role
    contract on the model's runtime. Pure; never raises for contract
    failures (callers decide) — resolution failures still raise."""
    report: list[CapabilityCheck] = []
    for role, resolution in registry.resolve_all().items():
        chain = [(resolution.primary, "primary")] + \
                [(name, "fallback") for name in resolution.fallbacks]
        for model, position in chain:
            report.append(_check_model(role, model, position,
                                       registry.models[model], registry,
                                       descriptors, capability_class, accelerator))
    return report


def _tool_call_parser(entry: ModelEntry, descriptor: RuntimeDescriptor) -> str:
    parsers = descriptor.capabilities.tool_call_parsers
    return entry.tool_call_format if entry.tool_call_format in parsers else ""


# ── slot runtime selection (PROVIDER_ABSTRACTION §4) ─────────────────────────


def _select_runtime(registry: RegistryV2, active: dict[str, ModelEntry],
                    runtime: str | None) -> str:
    by_runtime: dict[str, list[str]] = {}
    for name, entry in active.items():
        by_runtime.setdefault(entry.provider, []).append(name)
    if not by_runtime:
        raise RenderError("no active model — nothing to serve (activate a "
                          "model before rendering)")
    if runtime is None:
        if len(by_runtime) == 1:
            return next(iter(by_runtime))
        listing = "; ".join(f"{rt}: {', '.join(names)}"
                            for rt, names in sorted(by_runtime.items()))
        raise RenderError(
            "active set spans several runtimes but one engine slot serves "
            f"one runtime ({listing}) — select the slot runtime (AI_RUNTIME) "
            "and retire, or side-load, the models on the others")
    foreign = {rt: names for rt, names in by_runtime.items() if rt != runtime}
    if foreign:
        listing = "; ".join(f"{', '.join(names)} ({rt})"
                            for rt, names in sorted(foreign.items()))
        raise RenderError(
            f"runtime '{runtime}' owns the engine slot but active models "
            f"need another runtime: {listing} — retire them, install a "
            f"variant served by '{runtime}', or switch the slot runtime")
    return runtime


# ── artifact renderers (each pure) ───────────────────────────────────────────


def _banner(lines: list[str], comment: str = "#") -> str:
    return "".join(f"{comment} {line}\n" for line in [GENERATED_BANNER, *lines])


def _dump(data: dict[str, Any]) -> str:
    return yaml.dump(data, Dumper=_ComposeDumper, sort_keys=False,
                     default_flow_style=False, allow_unicode=True)


class _Override(dict):
    """A mapping emitted with compose's ``!override`` tag — the rendered
    ``deploy`` section must REPLACE the base file's (a plain merge would keep
    an accelerator reservation the host does not have)."""


class _ComposeDumper(yaml.SafeDumper):
    pass


_ComposeDumper.add_representer(
    _Override,
    lambda dumper, data: dumper.represent_mapping("!override", dict(data)))
_NUMERIC = re.compile(r"^-?\d+(\.\d+)?$")
_ComposeDumper.add_representer(
    str,
    lambda dumper, data: dumper.represent_scalar(
        "tag:yaml.org,2002:str", data,
        # numbers-as-strings and compose interpolation stay unmistakably strings
        style='"' if data == "" or _NUMERIC.match(data) or data.startswith("${") else None))


def engine_api_base() -> str:
    return f"http://{ENGINE_HOST}:{ENGINE_PORT}/v1"


def render_litellm(registry: RegistryV2, resolutions: dict[str, Resolution],
                   served_ids: dict[str, str],
                   embedding: EmbeddingEntry | None = None) -> str:
    """LiteLLM config: one alias per served model + one ``role-*`` alias per
    role, all at the engine slot; platform sections preserved verbatim."""
    def entry(alias: str, served: str, api_base: str) -> dict[str, Any]:
        return {"model_name": alias,
                "litellm_params": {"model": f"openai/{served}",
                                   "api_base": api_base,
                                   "api_key": LOCAL_API_KEY}}

    model_list = [entry(name, served_ids[name], engine_api_base())
                  for name in served_ids]
    model_list += [entry(f"{ROLE_ALIAS_PREFIX}{role}",
                         served_ids[resolution.primary], engine_api_base())
                   for role, resolution in resolutions.items()]
    if embedding is not None:
        model_list.append(entry(embedding.alias, embedding.model,
                                embedding.api_base))
    body = {"model_list": model_list,
            "general_settings": dict(LITELLM_GENERAL_SETTINGS),
            "litellm_settings": dict(LITELLM_SETTINGS)}
    header = _banner([f"generation {registry.generation} · "
                      f"{len(served_ids)} served model(s), "
                      f"{len(resolutions)} role alias(es) → "
                      f"{ENGINE_HOST}:{ENGINE_PORT}"])
    return header + _dump(body)


def render_role_map(registry: RegistryV2, runtime: str = "") -> str:
    """The runtime role map in ADR-020 ``agent_model_map`` shape — loadable
    by the existing ``model_registry.load_model_registry``; fallback keys
    only when non-empty (byte-compatible with ``RegistryV2.role_map``)."""
    roles, fallbacks = registry.role_map()
    mapping: dict[str, Any] = {}
    for role in registry.roles:
        spec: dict[str, Any] = {"primary": roles[role]}
        if fallbacks.get(role):
            spec["fallback"] = list(fallbacks[role])
        mapping[role] = spec
    body: dict[str, Any] = {"generation": registry.generation}
    if runtime:
        body["runtime"] = runtime
    body["agent_model_map"] = mapping
    body["aliases"] = {role: f"{ROLE_ALIAS_PREFIX}{role}" for role in registry.roles}
    header = _banner([f"generation {registry.generation} · role → primary/"
                      "fallback chain (ADR-020 shape) and LiteLLM alias"])
    return header + _dump(body)


def render_capability_report(registry: RegistryV2, capability_class: str,
                             report: list[CapabilityCheck]) -> str:
    body = {"generation": registry.generation,
            "capability_class": capability_class,
            "all_ok": all(check.ok for check in report),
            "checks": [check.model_dump() for check in report]}
    header = _banner([f"generation {registry.generation} · capability "
                      f"negotiation on class {capability_class}"])
    return header + _dump(body)


def _model_context(name: str, entry: ModelEntry, descriptor: RuntimeDescriptor,
                   tuning: dict[str, str]) -> dict[str, str]:
    source = descriptor.source_for(entry.source)
    if source is None:
        raise RenderError(
            f"model '{name}' has no source in a format runtime "
            f"'{descriptor.runtime}' serves ({', '.join(descriptor.serves_formats)}) "
            "— install records the artifact")
    _fmt, ref = source
    model_file = ref.rstrip("/").rsplit("/", 1)[-1]
    return {
        "model_name": name,
        "model_ref": ref,
        "model_file": model_file,
        "model_path": f"{descriptor.weights.container_dir.rstrip('/')}/{model_file}",
        "model_ctx": str(_effective_context(entry, _ctx_budget(descriptor, tuning))),
        "tool_call_parser": _tool_call_parser(entry, descriptor),
    }


def slot_problems(descriptor: RuntimeDescriptor, accelerator: str,
                  served: dict[str, ModelEntry]) -> list[str]:
    """Can this runtime materialize this served set on this accelerator?
    Plain-language reasons when not (PROVIDER_ABSTRACTION §4)."""
    problems: list[str] = []
    if accelerator not in descriptor.accelerators:
        problems.append(
            f"runtime '{descriptor.runtime}' has no image for accelerator "
            f"kind '{accelerator}' (supports: "
            f"{', '.join(descriptor.accelerators)}) — select a runtime that "
            "supports it, or render with accelerator='none' for the CPU path")
    if len(served) > 1 and descriptor.materialize.multi is None:
        problems.append(
            f"runtime '{descriptor.runtime}' serves one model per engine "
            f"instance but {len(served)} are active "
            f"({', '.join(served)}) — keep one active (retire the others "
            "or move them to a side-load), or select a runtime with "
            "parallel_models")
    for name, entry in served.items():
        if descriptor.source_for(entry.source) is None:
            problems.append(
                f"model '{name}' has no source in a format runtime "
                f"'{descriptor.runtime}' serves "
                f"({', '.join(descriptor.serves_formats)}) — install records "
                "the artifact")
    return problems


def served_id_for(descriptor: RuntimeDescriptor, name: str, entry: ModelEntry,
                  capability_class: str, accelerator: str = "none") -> str:
    """The id the engine answers to for a registry model (descriptor
    ``materialize.served_id`` template) — LiteLLM and probes address it."""
    tuning = descriptor.tuning_for(capability_class, accelerator)
    return _fill(descriptor.materialize.served_id,
                 _model_context(name, entry, descriptor, tuning),
                 f"descriptor '{descriptor.runtime}' materialize.served_id")


def materialize_service(descriptor: RuntimeDescriptor, vector: CapabilityVector,
                        capability_class: str, accelerator: str,
                        served: dict[str, ModelEntry],
                        rendered_dir_rel: str = f"./config/{RENDERED_DIRNAME}",
                        ) -> tuple[dict[str, Any], str | None]:
    """``materialize(model_set, vector) → engine spec``: the compose service
    mapping for the engine slot (+ the multi-model preset text when the
    runtime hosts several models). Everything runtime-specific comes from
    the descriptor. ``deploy`` is returned as an ``_Override`` mapping (a
    dict subclass) so the compose renderer can tag it; standalone consumers
    (the PR-4 side-load) may use it as a plain dict."""
    origin = f"descriptor '{descriptor.runtime}'"
    problems = slot_problems(descriptor, accelerator, served)
    if problems:
        raise RenderError("; ".join(problems))
    entry = descriptor.accelerators[accelerator]

    builtins = {
        "port": str(ENGINE_PORT),
        "cpu_cores": str(max(1, vector.cpu_cores)),
        "served_count": str(len(served)),
        "runtime": descriptor.runtime,
        "capability_class": capability_class,
        "accelerator": accelerator,
        "path": descriptor.verbs.ready.path,
    }
    tuning = {key: _fill(value, builtins, f"{origin} tuning.{key}")
              for key, value in descriptor.tuning_for(capability_class, accelerator).items()}
    context = {**builtins, **tuning}

    multi = descriptor.materialize.multi
    preset_text: str | None = None
    if len(served) == 1 or multi is None:
        name, model = next(iter(served.items()))
        model_ctx = {**context, **_model_context(name, model, descriptor, tuning)}
        command = [_fill(arg, model_ctx, f"{origin} materialize.single")
                   for arg in descriptor.materialize.single.command]
        if model_ctx["tool_call_parser"]:
            command += [_fill(arg, model_ctx, f"{origin} tool_calling_args")
                        for arg in descriptor.materialize.single.tool_calling_args]
        command += [_fill(arg, model_ctx, f"{origin} accelerators.{accelerator}.args")
                    for arg in entry.args]
        extra_volumes: list[str] = []
    else:
        context["preset_path"] = multi.preset.container_path
        command = [_fill(arg, context, f"{origin} materialize.multi")
                   for arg in multi.command]
        common = {**multi.preset.common, **entry.preset}
        lines = ["version = 1", "", "[*]"]
        lines += [f"{key} = {_fill(value, context, f'{origin} preset.common')}"
                  for key, value in common.items()]
        for name, model in served.items():
            model_ctx = {**context, **_model_context(name, model, descriptor, tuning)}
            lines += ["", f"[{name}]"]
            lines += [f"{key} = {_fill(value, model_ctx, f'{origin} preset.per_model')}"
                      for key, value in multi.preset.per_model.items()]
        preset_text = "\n".join(lines) + "\n"
        extra_volumes = [f"{rendered_dir_rel.rstrip('/')}/{PRESET_FILENAME}:"
                         f"{multi.preset.container_path}:ro"]

    weights = descriptor.weights
    service: dict[str, Any] = {
        "image": _fill(entry.image, context, f"{origin} accelerators.{accelerator}.image"),
        "command": command,
        "volumes": [f"{weights.host_dir}:{weights.container_dir}"
                    + (":ro" if weights.read_only else ""), *extra_volumes],
    }
    ready = descriptor.verbs.ready
    if ready.healthcheck:
        service["healthcheck"] = {
            "test": [_fill(part, context, f"{origin} verbs.ready.healthcheck")
                     for part in ready.healthcheck],
            "interval": f"{ready.interval_s}s",
            "timeout": "10s",
            "retries": ready.retries,
            "start_period": f"{ready.start_period_s}s",
        }
    extras = _merge(_fill_deep(descriptor.service, context, f"{origin} service"),
                    _fill_deep(entry.compose, context,
                               f"{origin} accelerators.{accelerator}.compose"))
    service = _merge(service, extras)
    if "deploy" in service:
        service["deploy"] = _Override(service["deploy"])
    return service, preset_text


def render_engine(registry: RegistryV2, descriptor: RuntimeDescriptor,
                  vector: CapabilityVector, capability_class: str,
                  accelerator: str, served: dict[str, ModelEntry],
                  rendered_dir_rel: str) -> tuple[str, str | None]:
    """Engine-slot materialization as the rendered compose override text."""
    service, preset_text = materialize_service(
        descriptor, vector, capability_class, accelerator, served, rendered_dir_rel)
    header = _banner([
        f"generation {registry.generation} · runtime {descriptor.runtime} · "
        f"class {capability_class} · accelerator {accelerator} · "
        f"serving {', '.join(served)}",
        f"engine slot = service '{ENGINE_SERVICE}' (historical name, ADR-001), "
        f"network alias '{ENGINE_HOST}' (ADR-026 R-3)",
        f"use: docker compose -f docker-compose.yml -f "
        f"{rendered_dir_rel.rstrip('/')}/{ENGINE_COMPOSE_FILENAME} up -d",
    ])
    return header + _dump({"services": {ENGINE_SERVICE: service}}), preset_text


# ── the generation render (atomic: all artifacts or one aggregated error) ────


def render(registry: RegistryV2, descriptors: dict[str, RuntimeDescriptor],
           vector: CapabilityVector, *, capability_class: str | None = None,
           accelerator: str | None = None, runtime: str | None = None,
           embedding: EmbeddingEntry | None = None,
           rendered_dir_rel: str = f"./config/{RENDERED_DIRNAME}") -> RenderResult:
    """Render one generation. Pure — returns texts; ``write_rendered``
    persists them. Raises ``RenderError`` listing every problem when the
    generation is not servable as declared."""
    capability_class = capability_class or classify(vector)
    accelerator = accelerator or vector.accelerator

    resolutions = registry.resolve_all()
    report = negotiate(registry, descriptors, capability_class, accelerator)
    problems = [f"{check.role} → {check.model} ({check.position}): {failure}"
                for check in report for failure in check.failures]

    active = {name: entry for name, entry in registry.models.items()
              if entry.state == "active"}
    descriptor: RuntimeDescriptor | None = None
    slot_runtime = runtime or ""
    try:
        slot_runtime = _select_runtime(registry, active, runtime)
    except RenderError as exc:
        problems.append(str(exc))
    else:
        descriptor = descriptors.get(slot_runtime)
        if descriptor is None:
            problems.append(f"runtime '{slot_runtime}' has no descriptor under "
                            "config/providers/ (known: "
                            + ", ".join(sorted(descriptors)) + ")")
        else:
            problems += slot_problems(descriptor, accelerator, active)
    if problems or descriptor is None:
        raise RenderError(
            f"generation {registry.generation} cannot be rendered — "
            f"{len(problems)} problem(s):\n- " + "\n- ".join(problems))

    compose_text, preset_text = render_engine(
        registry, descriptor, vector, capability_class, accelerator, active,
        rendered_dir_rel)
    served_ids = {name: served_id_for(descriptor, name, entry, capability_class, accelerator)
                  for name, entry in active.items()}

    artifacts = {
        LITELLM_FILENAME: render_litellm(registry, resolutions, served_ids, embedding),
        ENGINE_COMPOSE_FILENAME: compose_text,
        ROLE_MAP_FILENAME: render_role_map(registry, slot_runtime),
        CAPABILITY_REPORT_FILENAME: render_capability_report(
            registry, capability_class, report),
    }
    if preset_text is not None:
        artifacts[PRESET_FILENAME] = preset_text
    return RenderResult(
        generation=registry.generation, runtime=slot_runtime,
        capability_class=capability_class, accelerator=accelerator,
        served_models=list(active), artifacts=artifacts, report=report)


# ── persistence + drift detection (MODEL_LIFECYCLE §5) ───────────────────────


def rendered_dir(config_dir: Path) -> Path:
    return Path(config_dir) / RENDERED_DIRNAME


def _digest(text: str) -> str:
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()


def _read_manifest(out_dir: Path) -> dict[str, Any] | None:
    path = out_dir / MANIFEST_FILENAME
    if not path.is_file():
        return None
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data if isinstance(data, dict) else {}


def check_drift(out_dir: Path) -> list[str]:
    """What stands between the renderer and ``out_dir``: hand-edited
    artifacts (hash mismatch vs the manifest) and unmanaged files carrying
    a managed name. Empty list = safe to render."""
    out_dir = Path(out_dir)
    manifest = _read_manifest(out_dir)
    recorded: dict[str, str] = (manifest or {}).get("artifacts", {}) or {}
    drift: list[str] = []
    for name in MANAGED_FILENAMES:
        path = out_dir / name
        if not path.is_file():
            continue
        if name not in recorded:
            drift.append(f"{name}: unmanaged file (no manifest entry) — the "
                         "renderer will not overwrite a file it did not write")
        elif _digest(path.read_text(encoding="utf-8")) != recorded[name]:
            drift.append(f"{name}: edited by hand since generation "
                         f"{(manifest or {}).get('generation', '?')} "
                         "(content hash differs from the manifest)")
    return drift


def write_rendered(result: RenderResult, out_dir: Path, *,
                   force: bool = False) -> list[Path]:
    """Persist a render atomically per file and record the manifest.
    Refuses on drift unless ``force`` (the human decision to discard a
    manual edit is explicit, never implied). Artifacts of the previous
    render that this one no longer produces are removed."""
    out_dir = Path(out_dir)
    drift = check_drift(out_dir)
    if drift and not force:
        raise DriftError(
            f"refusing to render into {out_dir}:\n- " + "\n- ".join(drift)
            + "\nRendered files are outputs, not config: revert the edit and "
              "change state via `local-ezai model …`, or pass force=True to "
              "discard the manual changes.")
    out_dir.mkdir(parents=True, exist_ok=True)

    previous = _read_manifest(out_dir) or {}
    written: list[Path] = []
    for name, text in result.artifacts.items():
        path = out_dir / name
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(path)
        written.append(path)
    for stale in set(previous.get("artifacts") or {}) - set(result.artifacts):
        (out_dir / stale).unlink(missing_ok=True)

    manifest = {
        "generation": result.generation,
        "runtime": result.runtime,
        "capability_class": result.capability_class,
        "accelerator": result.accelerator,
        "served_models": result.served_models,
        "artifacts": {name: _digest(text) for name, text in result.artifacts.items()},
    }
    manifest_path = out_dir / MANIFEST_FILENAME
    tmp = manifest_path.with_suffix(".yaml.tmp")
    tmp.write_text(_banner(["content hashes of every rendered artifact — "
                            "drift detection compares against these"])
                   + _dump(manifest), encoding="utf-8")
    tmp.replace(manifest_path)
    written.append(manifest_path)
    log.info("generation %d rendered to %s (%s, %s/%s)", result.generation,
             out_dir, result.runtime, result.capability_class, result.accelerator)
    return written
